version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: prestamos_db
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  app:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - PORT=3000
      - DATABASE_URL
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  dbdata:
